api_controller_get:
    path: /api/getRestJsonRequest
    controller: App\Controller\JsonRestController::getRestJsonRequest
    methods: [GET]

api_controller_post:
    path: /api/postRestJsonRequest
    controller: App\Controller\JsonRestController::postRestJsonRequest
    methods: [POST]

api_exchange_value_post:
    path: /api/exchange/values
    controller: App\Controller\ExchangeValuesController::postExchangeValuesRequest
    methods: [POST]

api_exchange_value_get_history_all:
    path: /api/exchange/all/values
    controller: App\Controller\ExchangeValuesController::getAllHistoryRows
    methods: [GET]
